DROP DATABASE IF EXISTS bookdb2;
DROP USER  `bookadmin`@`%`;
DROP USER  `bookuser`@`%`;
CREATE DATABASE IF NOT EXISTS bookdb2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER  `bookadmin`@`%` IDENTIFIED BY  'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `bookdb2`.* TO `bookadmin`@`%`;
CREATE USER `bookuser`@`%` IDENTIFIED  BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `bookdb2`.* TO `bookuser`@`%`;
FLUSH PRIVILEGES;